kafka:
  producer:
    bootstrapServers: 101.132.110.204:9092
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    maxBlockMs: 30000
  consumer:
    bootstrapServers: 101.132.110.204:9092
    keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
    valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
    enableAutoCommit: false
    sessionTimeoutMs: 25000
    maxPollRecords: 30

    groupId: group3
    testTopic: test3
    testTopicConsumerThreadNum: 3

